networks:
  mosquitto:
    driver: bridge
    name: mosquitto
services:  
  mosquitto:
#    image: sonnyyu/mosquitto
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mosquitto
    volumes:
      - ./config/mosquitto.conf:/mqtt/config/mosquitto.conf
      - ./certs/ca.crt:/mqtt/cert/ca.crt
      - ./certs/192.168.1.204.pem:/mqtt/cert/localhost.pem
      - ./certs/192.168.1.204.key:/mqtt/cert/localhost.key
      - data:/mosquitto/data
      - log:/mosquitto/log
    ports:
      - 8883:8883
#      - 9001:9001
    restart: unless-stopped
    networks:
      - mosquitto

volumes:
  data:
    name: data
  log:
    name: log
